subo la lista de botones de la Home y la lista con los lugares - v1
UTN-FRBA-Mobile/SafeOut pull request #2
Opened 2020-10-16 15:21 UTC by fedebelve

2020-10-16 16:20 UTC, mrodriguezarias requested changes

2020-10-16 16:20 UTC, mrodriguezarias commented on app/src/main/java/com/utn_frba_mobile_2020_c2/safeout/models/Place.kt
> +data class Place(val id:Int, val name: String, val addrress: String, val ocupation: Int, val imgResource: Int)
@fedebelve
- [ ] `address` está mal escrito
- [ ] `occupation` está mal escrito
- [ ] Estaría faltando una propiedad `category` para el tipo de lugar
- [ ] Estaría faltando una propiedad `location` para la ubicación geográfica del lugar
- [ ] Estaría faltando una propiedad `sections` para las secciones del lugar
- [ ] `occupation` debería ser una propiedad de `Section`, no de `Place`
- [ ] El backend no nos provee de imágenes para los lugares, con lo cual la propiedad `imgResource` la sacaría

[Acá](https://github.com/mrodriguezarias/salina#place) podés ver cuáles son las propiedades de un lugar que vienen del backend. Deberían coincidir con las que tenga esta clase.

2020-10-16 16:20 UTC, mrodriguezarias commented on app/src/main/java/com/utn_frba_mobile_2020_c2/safeout/others/ExtensionFunctions.kt
> +package com.utn_frba_mobile_2020_c2.safeout.others
@fedebelve Fijate que yo había creado una carpeta [extensions](https://github.com/UTN-FRBA-Mobile/SafeOut/tree/master/app/src/main/java/com/utn_frba_mobile_2020_c2/safeout/extensions) para poner ahí todas las extensions. Podrás mover este código ahí así queda más organizado?

2020-10-16 16:20 UTC, mrodriguezarias commented on app/src/main/res/layout/fragment_home.xml
> +        android:text="Buscar"
@fedebelve Este y todos los otros valores de `android:text` hardcodeados en este archivo, deberían estar en `strings.xml` y acá solo poner la referencia, i.e. "@string/lo_que_sea".

2020-10-16 16:20 UTC, mrodriguezarias commented on app/src/main/res/layout/fragment_placelist.xml
> +        android:layout_width="0dp"
@fedebelve Me suena raro esto. Cómo podría tener un `layout_width` de 0 dp?

2020-10-16 16:20 UTC, mrodriguezarias commented on app/src/main/res/values/strings.xml
> +    <string name="drawer_search">"Buscar "</string>
@fedebelve Las comillas esas alrededor de `Buscar` me parece que están de más

2020-10-16 16:20 UTC, mrodriguezarias commented on app/src/main/res/layout/fragment_placelist.xml
> +        android:layout_width="0dp"
En realidad acá en vez de este `TextView` pienso que debería haber una barra de búsqueda, no? Para buscar el lugar que quieras y que a partir de eso se actualice la `RecyclerView` que está abajo con los datos que le devuelva el backend.

2020-10-16 16:20 UTC, mrodriguezarias commented on app/src/main/java/com/utn_frba_mobile_2020_c2/safeout/activities/BaseActivity.kt
> +import kotlinx.android.synthetic.main.activity_drawer.*
@fedebelve Todos estos `imports` nuevos en este archivo sirven para algo? Si no se usan pienso que sería mejor borrarlos.

2020-10-16 22:33 UTC, fedebelve commented on app/src/main/res/layout/fragment_placelist.xml
> +        android:layout_width="0dp"
sí, exactamente. Me quedó ese TVW pero está mal. lo saqué y ahí deberíamos agregar un filtro

2020-10-17 15:14 UTC, mrodriguezarias approved these changes

2020-10-19 13:55 UTC, merged